### PR TITLE
Add PVI integration

### LINKED ISSUE #119: Integrate PVI into ibek
In order to progress #110.

On 6 Oct we came up with the following:

1. Add an opi section to each definition in support YAML. Trial example [here](https://github.com/epics-containers/ibek-support/blob/253c352d62ee32e09131728460de051164903d2f/ADCore/ADCore.ibek.support.yaml#L1564-L1571)
2. Change Support YAML schema to match. (Already Done Here)[https://github.com/epics-containers/ibek/blob/53f0aa317693b90e41c70a7d4eb20fd7985f1295/src/ibek/support.py#L205-L207]3. 
4. update the `ibek support generate-links` command to copy bobs and pvi files into the `/epic/links` folder. This probably requires extra arguments to specify which hand-crafted bobs should be copied. [See Here](https://github.com/epics-containers/ibek/blob/12e2d1995e33a20d4cea17481f20ac22deba2bcc/src/ibek/support_cmds/commands.py#L259)
5. update `ibek runtime generate` to make bob files from PVI files at IOC instance launch time. [See Here](https://github.com/epics-containers/ibek/blob/53f0aa317693b90e41c70a7d4eb20fd7985f1295/src/ibek/runtime_cmds/commands.py) This function will also generate the required index.bob for the IOC - this needs to be a button for each screen instance with the PREFIX macro set accordingly.

Note that we were undecided about whether generated screens should have a PREFIX macro or should use $(P):$(R) or whatever the unique identifier is for the given support module.

Some work already started in `pvi-changes` branches of `ibek` and `ioc-adaravis`
Gary will do this work to get an intro to ibek.

### PR DESCRIPTION
**Pull request by GDYendell**
Closes #119

### CODE REVIEW

**Review by gilesknap — COMMENTED** [review]
no issues with the code changes! 
now trying it out ...

**Comment by gilesknap** [comment]
ouch!

If only I had done the pydantic conversion!

Do I need an Asyn definition? The top of my asynNDArrayDriver.pvi.device.yaml looks like this
I also recall you Capitalising th asyn in this file before....

```yaml
label: asynNDArrayDriver
parent: asynPortDriver
children:
  - type: Group
    name: ADSetup
    layout:
```

```
+ defs='/epics/ibek-defs/*.ibek.support.yaml'
+ ibek runtime generate /epics/ioc-adaravis/ioc/config/ioc.yaml /epics/ibek-defs/ADAravis.ibek.support.yaml /epics/ibek-defs/ADCore.ibek.support.yaml /epics/ibek-defs/asyn.ibek.support.yaml /epics/ibek-defs/autosave.ibek.support.yaml /epics/ibek-defs/epics.ibek.support.yaml /epics/ibek-defs/iocStats.ibek.support.yaml --out /tmp/st.cmd --db-out /tmp/ioc.subst
Traceback (most recent call last):

  File "/venv/bin/ibek", line 8, in <module>
    sys.exit(cli())

  File "/repos/ibek/src/ibek/runtime_cmds/commands.py", line 49, in generate
    pvi_index_entries, pvi_databases = generate_pvi(ioc_instance)

  File "/repos/ibek/src/ibek/runtime_cmds/commands.py", line 94, in generate_pvi
    device.deserialize_parents([PVI_DEFS])

  File "/repos/pvi/src/pvi/device.py", line 396, in deserialize_parents
    parent_parameters = find_components(self.parent, yaml_paths)

  File "/repos/pvi/src/pvi/device.py", line 437, in find_components
    list(find_components(device.parent, yaml_paths))

  File "/repos/pvi/src/pvi/device.py", line 437, in find_components
    list(find_components(device.parent, yaml_paths))

  File "/repos/pvi/src/pvi/device.py", line 434, in find_components
    device = Device.deserialize(device_yaml)

  File "/repos/pvi/src/pvi/device.py", line 389, in deserialize
    return deserialize(cls, YAML(typ="safe").load(serialized))

  File "/venv/lib/python3.10/site-packages/apischema/deserialization/__init__.py", line 887, in deserialize
    return deserialization_method(

  File "apischema/deserialization/methods.pyx", line 504, in apischema.deserialization.methods.ObjectMethod.deserialize

  File "apischema/deserialization/methods.pyx", line 505, in apischema.deserialization.methods.ObjectMethod.deserialize

  File "apischema/deserialization/methods.pyx", line 1077, in apischema.deserialization.methods.ObjectMethod_deserialize

apischema.validation.errors.ValidationError: ValidationError: [{'loc': ['children', 6, 'children'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'children'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'children'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'children'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'children'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'children'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'layout'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'layout'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'layout'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'layout'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'layout'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'layout'], 'err': 'unexpected property'}, {'loc': ['children', 6, 'macros'], 'err': 'missing property'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'name'], 'err': 'not matching pattern ([A-Z][a-z0-9]*)*$ (pattern)'}, {'loc': ['children', 6, 'pv'], 'err': 'missing property'}, {'loc': ['children', 6, 'pv'], 'err': 'missing property'}, {'loc': ['children', 6, 'pv'], 'err': 'missing property'}, {'loc': ['children', 6, 'pv'], 'err': 'missing property'}, {'loc': ['children', 6, 'pv'], 'err': 'missing property'}, {'loc': ['children', 6, 'type'], 'err': "not one of ['SignalR'] (oneOf)"}, {'loc': ['children', 6, 'type'], 'err': "not one of ['SignalW'] (oneOf)"}, {'loc': ['children', 6, 'type'], 'err': "not one of ['SignalRW'] (oneOf)"}, {'loc': ['children', 6, 'type'], 'err': "not one of ['SignalX'] (oneOf)"}, {'loc': ['children', 6, 'type'], 'err': "not one of ['DeviceRef'] (oneOf)"}, {'loc': ['children', 6, 'type'], 'err': "not one of ['SignalRef'] (oneOf)"}, {'loc': ['children', 6, 'ui'], 'err': 'missing property'}]
```

**Comment by gilesknap** [comment]
One more question - do we have a schema for device.yaml. If so I can use vscode to debug the yaml itself.

**Comment by gilesknap** [comment]
ooops

**Comment by GDYendell** [comment]
If there is no schema error, it is probably the name case thing. Check `label` and `name` fields and make sure they start with a capital.

**Comment by gilesknap** [comment]
OK that did it - no more schema errors - but I needed to change quite a few places. I assume we can fix the generator to not make this mistake (and maybe include the restriction in the schema).

I'm now getting 
```
OSError: Cannot find AsynPortDriver.pvi.device.yaml in [PosixPath('/epics/pvi-defs')]
```
which is correct - will try and generate a AsynPortDriver

**Comment by GDYendell** [comment]
> AsynPortDriver.pvi.device.yaml

This should start with a lower case to match the driver name. I generated the pvi yamls [here](https://github.com/epics-containers/ibek-support/tree/pvi/ADCore).

**Comment by gilesknap** [comment]
Thanks - but that is the AsynPortDriver itself from Asyn I assume. 

Your link does not have one of these and I can't convince PVI to build one. (not sure which DB I should use but its the .h file it doesn't like I think.

```
(venv) [hgv27681@pc0116 ~]$ pvi convert device /tmp /dls_sw/prod/R3.14.12.7/support/asyn/4-41/asyn/asynPortDriver/asynPortDriver.h --template /dls_sw/prod/R3.14.12.7/support/asyn/4-41/asyn/asynRecord/asynRecord.db Traceback (most recent call last):

  File "/scratch/hgv27681/work/venv/bin/pvi", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/scratch/hgv27681/work/venv/lib/python3.11/site-packages/pvi/__main__.py", line 104, in device
    name, parent = extract_device_and_parent_class(h.read_text())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/scratch/hgv27681/work/venv/lib/python3.11/site-packages/pvi/_convert/utils.py", line 10, in extract_device_and_parent_class
    assert match, "Can't find classes"

AssertionError: Can't find classes

```

**Comment by gilesknap** [comment]
We have lift-off!!

I removed the ref to AsynPortDriver that I mentioned above https://github.com/epics-containers/ibek/pull/132#issuecomment-1802441854

It now works. and I get
image

**Comment by GDYendell** [comment]
@gilesknap I added the last tweaks, visible in the compare changes [here](https://github.com/epics-containers/ibek/compare/c12b33f76821182251a479487fc744cfc80f24a9..e3071248161c82069cc88be78bdc84214d67e862).

I know you said it should avoid using `if definitions` because it is bad practice if it is None, but given the typer weirdness it really is a list, so I think this is the most correct check. I also added a comment in the code about this for clarity.

I will leave you to press the merge button in case there are any issues with this.

**Comment by gilesknap** [comment]
Yep I'm happy with the if definitions thing.

**Pull request merged**
